// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChqvnfq8CDFIhJBxKfhjiounGpOiVoUXE',
    appId: '1:411601119457:web:6cf48e12dd418c75cdefa0',
    messagingSenderId: '411601119457',
    projectId: 'dogear2',
    authDomain: 'dogear2.firebaseapp.com',
    storageBucket: 'dogear2.appspot.com',
    measurementId: 'G-72KNRGCY1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcAKEWXZgJz-UikX04x4ktgGmJ7cM_iJE',
    appId: '1:411601119457:android:f9a582e79989e139cdefa0',
    messagingSenderId: '411601119457',
    projectId: 'dogear2',
    storageBucket: 'dogear2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-SVD4xqmFiTj8Vo0L6lYj8w44fy0eu4',
    appId: '1:411601119457:ios:7144ae3db74884f1cdefa0',
    messagingSenderId: '411601119457',
    projectId: 'dogear2',
    storageBucket: 'dogear2.appspot.com',
    iosBundleId: 'com.example.dogear2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz-SVD4xqmFiTj8Vo0L6lYj8w44fy0eu4',
    appId: '1:411601119457:ios:9309ac09a9331e75cdefa0',
    messagingSenderId: '411601119457',
    projectId: 'dogear2',
    storageBucket: 'dogear2.appspot.com',
    iosBundleId: 'com.example.dogear2.RunnerTests',
  );
}
